<?php
// Automatically Generated by TestLink Installer - Mon, 07 Jul 14 01:46:23 -0400
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'Eqp9qH9Pya9FMVyV');
define('DB_HOST', '192.168.60.47');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
